// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  color_changer: dynamic(() => import("./ColorChanger")),
  heroo: dynamic(() => import("./Heroo")),
  marquee: dynamic(() => import("./Marquee")),
  purchase_button: dynamic(() => import("./PurchaseButton")),
  switch_playground: dynamic(() => import("./SwitchPlayground")),
};
